# Generated by Django 4.2.2 on 2024-04-04 10:53

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="StationInfo",
            fields=[
                ("id_station", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "station_name",
                    models.CharField(max_length=30, verbose_name="Название"),
                ),
                ("region", models.CharField(max_length=30, verbose_name="Регион")),
                (
                    "latitude",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Широта",
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Долгота",
                    ),
                ),
            ],
        ),
    ]
